version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    platform: linux/x86_64
    image: mysql:8.0.34
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_USER=$MYSQLDB_USER
      - MYSQL_PASSWORD=$MYSQLDB_ROOT_PASSWORD
    ports:
      - $MYSQLDB_OUT_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
    networks:
      - test1net
  app:
    container_name: app
    depends_on:
      - mysqldb
    build: ./
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_OUT_PORT:$SPRING_DOCKER_PORT
    volumes:
      - .m2:/root/.m2
    networks:
      - test1net
  webserver:
    image: nginx:1.15-alpine
    depends_on:
      - app
    restart: on-failure
    volumes:
      - ./nginx-certbot-master/data/certbot/conf:/etc/letsencrypt
      - ./nginx-certbot-master/data/certbot/www:/var/www/certbot
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    networks:
      - test1net
networks:
  test1net:
    driver: bridge

volumes:
  db: