spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: https://blackholenote.shop/login/oauth2/code/{registrationId}
            scope:
              - email
              - profile
